FROM python:3.13.5-slim

WORKDIR /app

# Install dependencies directly with pip
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    scikit-learn \
    xgboost \
    pandas \
    numpy \
    matplotlib \
    seaborn

# Copy application files
COPY app.py predict.py train.py ./
COPY loan_approval.csv Random_Forest_Model.bin ./

# Expose port
EXPOSE 8000

# Run app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
