FROM python:3.13.5-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn scikit-learn xgboost pandas numpy

COPY app.py predict.py train.py ./
COPY loan_approval.csv Random_Forest_Model.bin ./

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
